insert into Airports(Code,City,Country)  values('ABJ','ABIDJAN','Côte d’Ivoire');
insert into Airports(Code,City,Country)  values('AUH','ABOU DABI','Emirats arabes unis');
insert into Airports(Code,City,Country)  values('ABV','ABUJA','Nigeria');
insert into Airports(Code,City,Country)  values('ACC','ACCRA','Ghana');
insert into Airports(Code,City,Country)  values('ADA','ADANA','Turquie');
insert into Airports(Code,City,Country)  values('ADD','ADDIS ABABA','Éthiopie');
insert into Airports(Code,City,Country)  values('ADL','ADÉLAÏDE','Australie');
insert into Airports(Code,City,Country)  values('AGA','AGADIR','Maroc');
insert into Airports(Code,City,Country)  values('AAN','AL AIN','Emirats arabes unis');
insert into Airports(Code,City,Country)  values('AHU','AL HOCEIMA','Maroc');
insert into Airports(Code,City,Country)  values('ALB','ALBANY','Etats-Unis');
insert into Airports(Code,City,Country)  values('HBE','ALEXANDRIE','Egypte');
insert into Airports(Code,City,Country)  values('ALG','ALGER','Algérie');
insert into Airports(Code,City,Country)  values('ALC','ALICANTE','Espagne');
insert into Airports(Code,City,Country)  values('AMM','AMMAN','Jordanie');
insert into Airports(Code,City,Country)  values('AMS','AMSTERDAM','Pays Bas');
insert into Airports(Code,City,Country)  values('CRK','ANGELES','Philippines');
insert into Airports(Code,City,Country)  values('ESB','ANKARA','Turquie');
insert into Airports(Code,City,Country)  values('AYT','ANTALYA','Turquie');
insert into Airports(Code,City,Country)  values('OVD','ASTURIES','Espagne');
insert into Airports(Code,City,Country)  values('ATH','ATHÈNES','Grece');
insert into Airports(Code,City,Country)  values('ATL','ATLANTA','Etats-Unis');
insert into Airports(Code,City,Country)  values('AUS','AUSTIN','Etats-Unis');
insert into Airports(Code,City,Country)  values('BAH','BAHREÏN','Bahrain');
insert into Airports(Code,City,Country)  values('BKO','BAMAKO','Mali');
insert into Airports(Code,City,Country)  values('BKK','BANGKOK','Thailand');
insert into Airports(Code,City,Country)  values('BGR','BANGOR','Etats-Unis');
insert into Airports(Code,City,Country)  values('BGF','BANGUI','République centrafricaine');
insert into Airports(Code,City,Country)  values('BJL','BANJUL','Gambie');
insert into Airports(Code,City,Country)  values('BCN','BARCELONE','Espagne');
insert into Airports(Code,City,Country)  values('BRI','BARI','Italie');
insert into Airports(Code,City,Country)  values('TXL','BERLIN','Allemagne');
insert into Airports(Code,City,Country)  values('BEY','BEYROUTH','Liban');
insert into Airports(Code,City,Country)  values('BIO','BILBAO','Espagne');
insert into Airports(Code,City,Country)  values('OXB','BISSAU','Guinée-Bissau');
insert into Airports(Code,City,Country)  values('BJV','BODRUM','Turquie');
insert into Airports(Code,City,Country)  values('BOG','BOGOTA','Colombie');
insert into Airports(Code,City,Country)  values('BLQ','BOLOGNE','Italie');
insert into Airports(Code,City,Country)  values('BOM','BOMBAY','Inde');
insert into Airports(Code,City,Country)  values('BOD','BORDEAUX','France');
insert into Airports(Code,City,Country)  values('BOS','BOSTON','Etats-Unis');
insert into Airports(Code,City,Country)  values('UAR','BOUARFA','Maroc');
insert into Airports(Code,City,Country)  values('BZV','BRAZZAVILLE','Congo-Brazzaville');
insert into Airports(Code,City,Country)  values('BDS','BRINDISI','Italie');
insert into Airports(Code,City,Country)  values('BRU','BRUXELLES','Belgique');
insert into Airports(Code,City,Country)  values('OTP','BUCAREST','Romanie');
insert into Airports(Code,City,Country)  values('BUD','BUDAPEST','Hongrie');
insert into Airports(Code,City,Country)  values('EZE','BUENOS AIRES','Argentine');
insert into Airports(Code,City,Country)  values('BUF','BUFFALO','Etats-Unis');
insert into Airports(Code,City,Country)  values('BTV','BURLINGTON','Etats-Unis');
insert into Airports(Code,City,Country)  values('BEM','BÉNI MELLAL','Maroc');
insert into Airports(Code,City,Country)  values('CAI','CAIRE','Egypte');
insert into Airports(Code,City,Country)  values('YYC','CALGARY','Canada');
insert into Airports(Code,City,Country)  values('CAN','CANTON','Chine');
insert into Airports(Code,City,Country)  values('CTA','CATANE','Italie');
insert into Airports(Code,City,Country)  values('CEB','CEBU','Philippines');
insert into Airports(Code,City,Country)  values('CHS','CHARLESTON','Etats-Unis');
insert into Airports(Code,City,Country)  values('CLT','CHARLOTTE','Etats-Unis');
insert into Airports(Code,City,Country)  values('ORD','CHICAGO','Etats-Unis');
insert into Airports(Code,City,Country)  values('CVG','CINCINNATI','Etats-Unis');
insert into Airports(Code,City,Country)  values('CLE','CLEVELAND','Etats-Unis');
insert into Airports(Code,City,Country)  values('CMB','COLOMBO','Sri Lanka');
insert into Airports(Code,City,Country)  values('CKY','CONAKRY','Guinée');
insert into Airports(Code,City,Country)  values('COO','COTONOU','Bénin');
insert into Airports(Code,City,Country)  values('DAC','DACCA','Bangladesh');
insert into Airports(Code,City,Country)  values('DSS','DAKAR','Sénégal');
insert into Airports(Code,City,Country)  values('VIL','DAKHLA','Maroc');
insert into Airports(Code,City,Country)  values('DLM','DALAMAN','Turquie');
insert into Airports(Code,City,Country)  values('DFW','DALLAS','Etats-Unis');
insert into Airports(Code,City,Country)  values('DMM','DAMMAM','Arabie Saoudite');
insert into Airports(Code,City,Country)  values('DAR','DAR ES SALAM','Tanzanie');
insert into Airports(Code,City,Country)  values('DEL','DELHI','Inde');
insert into Airports(Code,City,Country)  values('DPS','DENPASAR','Indonésie');
insert into Airports(Code,City,Country)  values('DEN','DENVER','Etats-Unis');
insert into Airports(Code,City,Country)  values('DTW','DETROIT','Etats-Unis');
insert into Airports(Code,City,Country)  values('JED','DJEDDAH','Arabie Saoudite');
insert into Airports(Code,City,Country)  values('JIB','DJIBOUTI','Djibouti');
insert into Airports(Code,City,Country)  values('DOH','DOHA','Qatar');
insert into Airports(Code,City,Country)  values('DLA','DOUALA','Cameroun');
insert into Airports(Code,City,Country)  values('DXB','DUBAI','Emirats arabes unis');
insert into Airports(Code,City,Country)  values('DUS','DUSSELDORF','Allemagne');
insert into Airports(Code,City,Country)  values('EDI','EDINBOURG','Royaume-Uni');
insert into Airports(Code,City,Country)  values('YEG','EDMONTON','Canada');
insert into Airports(Code,City,Country)  values('EIN','EINDHOVEN','Pays Bas');
insert into Airports(Code,City,Country)  values('EBB','ENTEBEE','Ouganda');
insert into Airports(Code,City,Country)  values('ERH','ERRACHIDIA','Maroc');
insert into Airports(Code,City,Country)  values('ESU','ESSAOUIRA','Maroc');
insert into Airports(Code,City,Country)  values('FLR','FLORENCE','Italie');
insert into Airports(Code,City,Country)  values('FLL','FORT LAUDERDALE','Etats-Unis');
insert into Airports(Code,City,Country)  values('FRA','FRANCFORT','Allemagne');
insert into Airports(Code,City,Country)  values('FNA','FREETOWN','Sierra Leone');
insert into Airports(Code,City,Country)  values('FEZ','FÈS','Maroc');
insert into Airports(Code,City,Country)  values('ELQ','GASSIM','Arabie Saoudite');
insert into Airports(Code,City,Country)  values('GZT','GAZIANTEP','Turquie');
insert into Airports(Code,City,Country)  values('GVA','GENÈVE','Suisse');
insert into Airports(Code,City,Country)  values('GIB','GIBRALTAR','Royaume-Uni');
insert into Airports(Code,City,Country)  values('GLA','GLASGOW','Royaume-Uni');
insert into Airports(Code,City,Country)  values('GSO','GREENSBORO/HIGH POINT','Etats-Unis');
insert into Airports(Code,City,Country)  values('GSP','GREENVILLE','Etats-Unis');
insert into Airports(Code,City,Country)  values('GLN','GUELMIM','Maroc');
insert into Airports(Code,City,Country)  values('GOA','GÊNES','Italie');
insert into Airports(Code,City,Country)  values('YHZ','HALIFAX','Canada');
insert into Airports(Code,City,Country)  values('HAM','HAMBOURG','Allemagne');
insert into Airports(Code,City,Country)  values('HAN','HANOI','Vietnam');
insert into Airports(Code,City,Country)  values('BDL','HARTFORD','Etats-Unis');
insert into Airports(Code,City,Country)  values('HTY','HATAY','Turquie');
insert into Airports(Code,City,Country)  values('HEL','HELSINKI','Finlande');
insert into Airports(Code,City,Country)  values('SGN','HO CHI MINH VILLE','Vietnam');
insert into Airports(Code,City,Country)  values('HOU','HOUSTON','Etats-Unis');
insert into Airports(Code,City,Country)  values('IAH','HOUSTON','Etats-Unis');
insert into Airports(Code,City,Country)  values('IBZ','IBIZA','Espagne');
insert into Airports(Code,City,Country)  values('SVX','IEKATERINBOURG','Russie');
insert into Airports(Code,City,Country)  values('IND','INDIANAPOLIS','Etats-Unis');
insert into Airports(Code,City,Country)  values('ISB','ISLAMABAD','Pakistan');
insert into Airports(Code,City,Country)  values('IST','ISTANBUL','Turquie');
insert into Airports(Code,City,Country)  values('ADB','IZMIR','Turquie');
insert into Airports(Code,City,Country)  values('JAX','JACKSONVILLE','Etats-Unis');
insert into Airports(Code,City,Country)  values('JKT','JAKARTA','Indonésie');
insert into Airports(Code,City,Country)  values('JNB','JOHANNESBURG','Afrique du Sud');
insert into Airports(Code,City,Country)  values('KGD','KALININGRAD','Russie');
insert into Airports(Code,City,Country)  values('MCI','KANSAS CITY','Etats-Unis');
insert into Airports(Code,City,Country)  values('KHI','KARACHI','Pakistan');
insert into Airports(Code,City,Country)  values('ASR','KAYSÉRI','Turquie');
insert into Airports(Code,City,Country)  values('KZN','KAZAN','Russie');
insert into Airports(Code,City,Country)  values('KRT','KHARTOUM','Soudan');
insert into Airports(Code,City,Country)  values('KBP','KIEV','Ukraine');
insert into Airports(Code,City,Country)  values('KGL','KIGALI','Rwanda');
insert into Airports(Code,City,Country)  values('JRO','KILIMANDJARO','Tanzanie');
insert into Airports(Code,City,Country)  values('FIH','KINSHASA','République démocratique du Congo');
insert into Airports(Code,City,Country)  values('KYA','KONYA','Turquie');
insert into Airports(Code,City,Country)  values('KWI','KOWEÏT','Kuwait');
insert into Airports(Code,City,Country)  values('KRR','KRASNODAR','Russie');
insert into Airports(Code,City,Country)  values('KJA','KRASNOYARSK','Russie');
insert into Airports(Code,City,Country)  values('KUL','KUALA LUMPUR','Malaysia');
insert into Airports(Code,City,Country)  values('LHE','LAHORE','Pakistan');
insert into Airports(Code,City,Country)  values('LCG','LA COROGNE','Espagne');
insert into Airports(Code,City,Country)  values('MSY','LA NOUVELLE ORLÉANS','Etats-Unis');
insert into Airports(Code,City,Country)  values('EUN','LAAYOUNE','Maroc');
insert into Airports(Code,City,Country)  values('LOS','LAGOS','Nigeria');
insert into Airports(Code,City,Country)  values('SUF','LAMEZIA TERME','Italie');
insert into Airports(Code,City,Country)  values('LCA','LARNACA','Chypre');
insert into Airports(Code,City,Country)  values('LPA','LAS PALMAS','Espagne');
insert into Airports(Code,City,Country)  values('LAS','LAS VEGAS','Etats-Unis');
insert into Airports(Code,City,Country)  values('CPT','LE CAP','Afrique du Sud');
insert into Airports(Code,City,Country)  values('LBV','LIBREVILLE','Gabon');
insert into Airports(Code,City,Country)  values('LIS','LISBONNE','Portugal');
insert into Airports(Code,City,Country)  values('LFW','LOMÉ','Togo');
insert into Airports(Code,City,Country)  values('LON','LONDRES','Royaume-Uni');
insert into Airports(Code,City,Country)  values('LGW','LONDRES','Royaume-Uni');
insert into Airports(Code,City,Country)  values('LHR','LONDRES','Royaume-Uni');
insert into Airports(Code,City,Country)  values('LAX','LOS ANGELES','Etats-Unis');
insert into Airports(Code,City,Country)  values('LAD','LUANDA','Angola');
insert into Airports(Code,City,Country)  values('LUN','LUSAKA','Zambia');
insert into Airports(Code,City,Country)  values('LYS','LYON','France');
insert into Airports(Code,City,Country)  values('MST','MAASTRICHT','Pays Bas');
insert into Airports(Code,City,Country)  values('MAD','MADRID','Espagne');
insert into Airports(Code,City,Country)  values('SSG','MALABO','Guinée équatoriale');
insert into Airports(Code,City,Country)  values('AGP','MALAGA','Espagne');
insert into Airports(Code,City,Country)  values('MAN','MANCHESTER','Royaume-Uni');
insert into Airports(Code,City,Country)  values('MNL','MANILLE','Philippines');
insert into Airports(Code,City,Country)  values('RAK','MARRAKECH','Maroc');
insert into Airports(Code,City,Country)  values('MRS','MARSEILLE','France');
insert into Airports(Code,City,Country)  values('MCT','MASCATE','Oman');
insert into Airports(Code,City,Country)  values('MED','MEDINA','Arabie Saoudite');
insert into Airports(Code,City,Country)  values('MEM','MEMPHIS','Etats-Unis');
insert into Airports(Code,City,Country)  values('MIA','MIAMI','Etats-Unis');
insert into Airports(Code,City,Country)  values('MXP','MILAN','Italie');
insert into Airports(Code,City,Country)  values('MKE','MILWAUKEE','Etats-Unis');
insert into Airports(Code,City,Country)  values('MSP','MINNEAPOLIS','Etats-Unis');
insert into Airports(Code,City,Country)  values('ROB','MONROVIA','Libéria');
insert into Airports(Code,City,Country)  values('MPL','MONTPELLIER','France');
insert into Airports(Code,City,Country)  values('YUL','MONTRÉAL','Canada');
insert into Airports(Code,City,Country)  values('MOW','MOSCOU','Russie');
insert into Airports(Code,City,Country)  values('DME','MOSCOU','Russie');
insert into Airports(Code,City,Country)  values('MUC','MUNICH','Allemagne');
insert into Airports(Code,City,Country)  values('NDJ','N’DJAMENA','Tchad');
insert into Airports(Code,City,Country)  values('NDR','NADOR','Maroc');
insert into Airports(Code,City,Country)  values('NBO','NAIROBI','Kenya');
insert into Airports(Code,City,Country)  values('NTE','NANTES','France');
insert into Airports(Code,City,Country)  values('NAP','NAPLES','Italie');
insert into Airports(Code,City,Country)  values('BNA','NASHVILLE','Etats-Unis');
insert into Airports(Code,City,Country)  values('JFK','NEW YORK','Etats-Unis');
insert into Airports(Code,City,Country)  values('NIM','NIAMEY','Niger');
insert into Airports(Code,City,Country)  values('NCE','NICE','France');
insert into Airports(Code,City,Country)  values('ORF','NORFOLK','Etats-Unis');
insert into Airports(Code,City,Country)  values('NKC','NOUAKCHOTT','Mauritanie');
insert into Airports(Code,City,Country)  values('OVB','NOVOSIBIRSK','Russie');
insert into Airports(Code,City,Country)  values('MCO','ORLANDO','Etats-Unis');
insert into Airports(Code,City,Country)  values('OSL','OSLO','Norvège');
insert into Airports(Code,City,Country)  values('YOW','OTTAWA','Canada');
insert into Airports(Code,City,Country)  values('OUA','OUAGADOUGOU','Burkina Faso');
insert into Airports(Code,City,Country)  values('OZZ','OUARZAZATE','Maroc');
insert into Airports(Code,City,Country)  values('OUD','OUJDA','Maroc');
insert into Airports(Code,City,Country)  values('PMO','PALERME','Italie');
insert into Airports(Code,City,Country)  values('PMI','PALMA DE MAJORQUE','Espagne');
insert into Airports(Code,City,Country)  values('PAR','PARIS','France');
insert into Airports(Code,City,Country)  values('CDG','PARIS','France');
insert into Airports(Code,City,Country)  values('ORY','PARIS','France');
insert into Airports(Code,City,Country)  values('PEE','PERM','Russie');
insert into Airports(Code,City,Country)  values('PER','PERTH','Australie');
insert into Airports(Code,City,Country)  values('PHL','PHILADELPHIE','Etats-Unis');
insert into Airports(Code,City,Country)  values('PNH','PHNOM PENH','Cambodge');
insert into Airports(Code,City,Country)  values('PHX','PHOENIX','Etats-Unis');
insert into Airports(Code,City,Country)  values('PSA','PISE','Italie');
insert into Airports(Code,City,Country)  values('PNR','POINTE NOIRE','Congo-Brazzaville');
insert into Airports(Code,City,Country)  values('PDX','PORTLAND','Etats-Unis');
insert into Airports(Code,City,Country)  values('OPO','PORTO','Portugal');
insert into Airports(Code,City,Country)  values('PRG','PRAGUE','République Tchèque');
insert into Airports(Code,City,Country)  values('RAI','PRAIA','Cap-Vert');
insert into Airports(Code,City,Country)  values('BJS','PÉKIN','Chine');
insert into Airports(Code,City,Country)  values('PKX','PÉKIN','Chine');
insert into Airports(Code,City,Country)  values('PEK','PÉKIN','Chine');
insert into Airports(Code,City,Country)  values('RBA','RABAT','Maroc');
insert into Airports(Code,City,Country)  values('RDU','RALEIGH/DURHAM','Etats-Unis');
insert into Airports(Code,City,Country)  values('REG','REGGIO DE CALABRE','Italie');
insert into Airports(Code,City,Country)  values('RUH','RIYAD','Arabie Saoudite');
insert into Airports(Code,City,Country)  values('ROC','ROCHESTER','Etats-Unis');
insert into Airports(Code,City,Country)  values('FCO','ROME','Italie');
insert into Airports(Code,City,Country)  values('ROV','ROSTOV','Russie');
insert into Airports(Code,City,Country)  values('RTM','ROTTERDAM','Pays Bas');
insert into Airports(Code,City,Country)  values('SCQ','SAINT JACQUES DE COMPOSTELLE','Espagne');
insert into Airports(Code,City,Country)  values('LED','SAINT-PÉTERSBOURG','Russie');
insert into Airports(Code,City,Country)  values('SLL','SALALAH','Oman');
insert into Airports(Code,City,Country)  values('KUF','SAMARA','Russie');
insert into Airports(Code,City,Country)  values('SFO','SAN FRANCISCO','Etats-Unis');
insert into Airports(Code,City,Country)  values('SDR','SANTANDER','Espagne');
insert into Airports(Code,City,Country)  values('SEA','SEATTLE','Etats-Unis');
insert into Airports(Code,City,Country)  values('SVQ','SEVILLE','Espagne');
insert into Airports(Code,City,Country)  values('SIN','SINGAPOUR','Singapour');
insert into Airports(Code,City,Country)  values('SOF','SOFIA','Bulgarie');
insert into Airports(Code,City,Country)  values('SXB','STRASBOURG','France');
insert into Airports(Code,City,Country)  values('SEL','SÉOUL','Corée du Sud');
insert into Airports(Code,City,Country)  values('ICN','SÉOUL','Corée du Sud');
insert into Airports(Code,City,Country)  values('TCI','TENERIFE','Espagne');
insert into Airports(Code,City,Country)  values('TFS','TENERIFE','Espagne');
insert into Airports(Code,City,Country)  values('TPA','TAMPA','Etats-Unis');
insert into Airports(Code,City,Country)  values('TTA','TAN-TAN','Maroc');
insert into Airports(Code,City,Country)  values('TNG','TANGER','Maroc');
insert into Airports(Code,City,Country)  values('TLV','TEL AVIV','Israel');
insert into Airports(Code,City,Country)  values('NRT','TOKYO','Japon');
insert into Airports(Code,City,Country)  values('YYZ','TORONTO','Canada');
insert into Airports(Code,City,Country)  values('TLS','TOULOUSE','France');
insert into Airports(Code,City,Country)  values('TRS','TRIESTE','Italie');
insert into Airports(Code,City,Country)  values('MJI','TRIPOLI','Jamahiriya Arabe Libyenne');
insert into Airports(Code,City,Country)  values('TUN','TUNIS','Tunisie');
insert into Airports(Code,City,Country)  values('TRN','TURIN','Italie');
insert into Airports(Code,City,Country)  values('TTU','TÉTOUAN','Maroc');
insert into Airports(Code,City,Country)  values('UFA','UFA','Russie');
insert into Airports(Code,City,Country)  values('VLC','VALENCE','Espagne');
insert into Airports(Code,City,Country)  values('YVR','VANCOUVER','Canada');
insert into Airports(Code,City,Country)  values('WAW','VARSOVIE','Pologne');
insert into Airports(Code,City,Country)  values('VCE','VENISE','Italie');
insert into Airports(Code,City,Country)  values('VIE','VIENNE','Autriche');
insert into Airports(Code,City,Country)  values('VGO','VIGO','Espagne');
insert into Airports(Code,City,Country)  values('WAS','WASHINGTON DC','Etats-Unis');
insert into Airports(Code,City,Country)  values('IAD','WASHINGTON DC','Etats-Unis');
insert into Airports(Code,City,Country)  values('BWI','WASHINGTON DC','Etats-Unis');
insert into Airports(Code,City,Country)  values('YWG','WINNIPEG','Canada');
insert into Airports(Code,City,Country)  values('NSI','YAOUNDÉ','Cameroun');
insert into Airports(Code,City,Country)  values('ZNZ','ZANZIBAR','Tanzanie');
insert into Airports(Code,City,Country)  values('OZG','ZAGORA','Maroc');
insert into Airports(Code,City,Country)  values('ZRH','ZURICH','Suisse');
insert into Airports(Code,City,Country)  values('SID','ÎLE DE SAL','Cap-Vert');
